[package]
name = "test-fixtures"
version = "0.1.0"
description = "Guest wasm programs intended for integration testing."
authors = ["Fastly"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"
publish = false

[dependencies]
fastly = "=0.8.1"
fastly-shared = "=0.8.1"
fastly-sys = "=0.8.1"
bytes = "1.0.0"
http = "0.2.1"
serde = "1.0.114"
